### PR TITLE
printing_auto_base: fix same record printed multiple times

### PR DESCRIPTION
**Pull request by TDu**
ref.: rau-231

### CODE REVIEW

**Review by jbaudoux — CHANGES_REQUESTED** [review]
You better call `_handle_print_auto(printing_auto)` on recordset instead of record.
Group records by printing_auto to build the recordset.

**Comment by TDu** [comment]
> You better call `_handle_print_auto(printing_auto)` on recordset instead of record. Group records by printing_auto to build the recordset.

IMO this will not fix the problem because `do_print` calls `_get_content` which calls `_get_record` https://github.com/jbaudoux/report-print-send/blob/9cc9676e4c2b710bb31bd967ee8cc18c65aa0488/printing_auto_base/models/printing_auto.py#L144

To fix this would need a refactor of the module, has explained on the related card.

**Comment by jbaudoux** [comment]
> > You better call `_handle_print_auto(printing_auto)` on recordset instead of record. Group records by printing_auto to build the recordset.
> 
> IMO this will not fix the problem because `do_print` calls `_get_content` which calls `_get_record`
> 
> https://github.com/jbaudoux/report-print-send/blob/9cc9676e4c2b710bb31bd967ee8cc18c65aa0488/printing_auto_base/models/printing_auto.py#L144
> 
> To fix this would need a refactor of the module, has explained on the related card.

Indeed, you need to rename record to records and remove record.ensure_one(). Not a big refactor ;)

**Comment by TDu** [comment]
> > > You better call `_handle_print_auto(printing_auto)` on recordset instead of record. Group records by printing_auto to build the recordset.
> > 
> > 
> > IMO this will not fix the problem because `do_print` calls `_get_content` which calls `_get_record`
> > https://github.com/jbaudoux/report-print-send/blob/9cc9676e4c2b710bb31bd967ee8cc18c65aa0488/printing_auto_base/models/printing_auto.py#L144
> > 
> > To fix this would need a refactor of the module, has explained on the related card.
> 
> Indeed, you need to rename record to records and remove record.ensure_one(). Not a big refactor ;)

The problem I see is more related to the `_get_record` called by `_get_content` and the use of `record_change`

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
